# Dependencies
markdown:         kramdown
highlighter: rouge


# Permalinks
permalink:        pretty




# Setup
title:            white-turtle
tagline:          'turtles and code!'
description:      "web-space of -  "
url:              https://white-turtle.org/

author:
  name:           'vishal basra'
  url:            https://twitter.com/vishalbasra

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
github:
  address: https://github.com/vishalbasra

linkedin:
  username: https://www.linkedin.com/in/vishal-basra-0506ba103/
