# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            white-turtle
tagline:          'turtles and code!'
description:      'Web-space of  <a href="https://twitter.com/vishalbasra" target="_blank">Vishal Basra!</a> '
url:              https://vishalbasra.github.io/
baseurl:          # the optional subpath of your site, e.g. "/blog"

author:
  name:           'Vishal Basra'
  url:            https://twitter.com/vishalbasra

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
github:
  address: https://github.com/vishalbasra
